
"""
State definitions for the forecasting agent workflow.
"""
from typing import TypedDict, Annotated, List, Union, Dict, Any

class AgentState(TypedDict):
    # The initial user prompt
    user_request: str

    # DQ Validation fields
    dq_status: str  # "valid" or "error"
    dq_error_message: str
    
    # Analyze the request to determine if we have tools or need new ones
    analysis: str

    groups_trends: str

    # The plan: list of steps or just the name of the tool needed
    tools: list[str]

    # The plan: list of steps or just the name of the tool needed
    tools_needed: list[str]
    
    # The code generated by the Coder LLM
    generated_code: list[str]
    
    # The result of the code execution (or tool execution)
    execution_result: Any
    
    # Final response to the user
    final_response: str

    # Chat history or detailed messages if needed
    messages: List[Dict[str, str]]
